language: java
sudo: false # faster builds

jobs:
  - sudo: required
    group: edge
    arch: arm64-graviton2
    virt: lxd
    dist: focal
    jdk: openjdk11

  - sudo: required
    group: edge
    arch: arm64-graviton2
    virt: lxd
    dist: focal
    jdk: openjdk8
    
jdk:
  - openjdk11
  - openjdk8

cache:
  directories:
    - $HOME/.m2

install: true

script:
  - export TESTCONTAINERS_RYUK_DISABLED=true
  - rm -rf $HOME/.m2/repository/org/glassfish/javax.el/3.0.1-b08
  - travis_wait 30 ./mvnw --batch-mode --no-transfer-progress clean install -Dcheckstyle.skip=false -Drat.skip=false -Dmaven.javadoc.skip=true

after_success:
  - bash <(curl -s https://codecov.io/bash)

after_failure:
  - echo "build failed!"
